name: Auto DailyNews

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 0:00 运行，相当于北京时间 8:00
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests termcolor

      - name: Run Python script
        run: |
          python run.py
        env:
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          # 在这里添加其他需要传递给 Python 脚本的 secret 环境变量